//
//  StyleKitName.h
//  ProjectName
//
//  Created by AuthorName on 8/11/14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKitName : NSObject

// Colors
+ (UIColor*)color;
+ (UIColor*)color2;
+ (UIColor*)color5;

// Drawing Methods
+ (void)drawCanvas1WithFrame: (CGRect)frame;

@end
